"""Initial migration.

Revision ID: 101574e504e9
Revises: 
Create Date: 2021-10-13 17:46:11.516389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101574e504e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('purpose', sa.Text(), nullable=True))
    op.alter_column('booking', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('booking', 'lecture_hall',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'start_time',
               existing_type=sa.TIME(),
               nullable=False)
    op.alter_column('booking', 'end_time',
               existing_type=sa.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'end_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('booking', 'start_time',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('booking', 'lecture_hall',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('booking', 'purpose')
    # ### end Alembic commands ###
